Repository ContainerRestaurant/ContainerRestaurant-Server, pull requests merged in 2021-06, with the labels that each got.

#97 :bug: 추천피드 요청시 마다 링크가 복사되는 버그 해결
  src/main/java/container/restaurant/server/domain/feed/recommend/RecommendFeedService.java
  src/main/java/container/restaurant/server/web/FeedController.java
Labels: bug

#100 푸시 관련 구현
  src/main/java/container/restaurant/server/domain/push/PushFeedEventHandler.java
  src/main/java/container/restaurant/server/domain/push/PushToken.java
  src/main/java/container/restaurant/server/domain/push/PushTokenRepository.java
  src/main/java/container/restaurant/server/domain/push/PushTokenService.java
  src/main/java/container/restaurant/server/domain/user/User.java
  src/main/java/container/restaurant/server/domain/user/UserRepository.java
  src/main/java/container/restaurant/server/domain/user/UserService.java
  src/main/java/container/restaurant/server/exception/UsingPushTokenException.java
  src/main/java/container/restaurant/server/utils/FirebaseCloudMessageUtils.java
  src/main/java/container/restaurant/server/web/PushController.java
  src/main/java/container/restaurant/server/web/PushTestController.java
  src/main/java/container/restaurant/server/web/dto/user/UserUpdateDto.java
  src/main/java/container/restaurant/server/web/linker/PushTokenLinker.java
  src/main/java/container/restaurant/server/web/util/ExceptionAdvice.java
  src/test/java/container/restaurant/server/web/UserControllerTest.java
Labels: enhancement

#99 :memo: 댓글 Docs 일부 추가
  src/docs/asciidoc/index.adoc
  src/main/java/container/restaurant/server/domain/comment/Comment.java
  src/main/java/container/restaurant/server/domain/comment/CommentService.java
  src/main/java/container/restaurant/server/web/CommentController.java
  src/main/java/container/restaurant/server/web/dto/comment/CommentCreateDto.java
  src/test/java/container/restaurant/server/web/CommentControllerTest.java
  src/test/java/container/restaurant/server/web/FeedControllerTest.java
  src/test/java/container/restaurant/server/web/base/BaseFeedAndCommentControllerTest.java
Labels: documentation

#101 푸쉬 토큰, 식당/즐겨찾기, 통계정보 Docs 구현
  src/docs/asciidoc/index.adoc
  src/main/java/container/restaurant/server/domain/restaurant/favorite/RestaurantFavoriteService.java
  src/main/java/container/restaurant/server/web/RestaurantController.java
  src/main/java/container/restaurant/server/web/RestaurantFavoriteController.java
  src/main/java/container/restaurant/server/web/UserController.java
  src/main/java/container/restaurant/server/web/dto/statistics/StatisticsInfoDto.java
  src/main/java/container/restaurant/server/web/linker/RestaurantFavoriteLinker.java
  src/main/java/container/restaurant/server/web/linker/RestaurantLinker.java
  src/test/java/container/restaurant/server/web/PushControllerTest.java
  src/test/java/container/restaurant/server/web/RestaurantControllerTest.java
  src/test/java/container/restaurant/server/web/RestaurantFavoriteControllerTest.java
  src/test/java/container/restaurant/server/web/StatisticsControllerTest.java
  src/test/java/container/restaurant/server/web/UserControllerTest.java
Labels: documentation

#104 :bug: 피드쓰기 썸네일이 Null인 경우 오류 수정
  src/main/java/container/restaurant/server/domain/feed/picture/ImageService.java
Labels: bug

#106 :sparkles: 내 정보 조회 기능 추가
  src/docs/asciidoc/index.adoc
  src/main/java/container/restaurant/server/config/auth/LoginUserFilter.java
  src/main/java/container/restaurant/server/web/IndexController.java
  src/main/java/container/restaurant/server/web/UserController.java
  src/main/java/container/restaurant/server/web/linker/UserLinker.java
  src/test/java/container/restaurant/server/web/IndexControllerTest.java
  src/test/java/container/restaurant/server/web/UserControllerTest.java
Labels: enhancement

#108 ✨ '/' 경로에 주위 식당 조회 링크 추가
  src/main/java/container/restaurant/server/web/IndexController.java
  src/main/java/container/restaurant/server/web/RestaurantController.java
  src/main/java/container/restaurant/server/web/UserController.java
  src/main/java/container/restaurant/server/web/linker/RestaurantLinker.java
  src/test/java/container/restaurant/server/web/IndexControllerTest.java
Labels: enhancement

#110 용기친화 식당 정보 추가
  src/main/java/container/restaurant/server/domain/feed/FeedRepository.java
  src/main/java/container/restaurant/server/domain/feed/FeedService.java
  src/main/java/container/restaurant/server/domain/restaurant/Restaurant.java
  src/main/java/container/restaurant/server/web/dto/feed/FeedDetailDto.java
  src/main/java/container/restaurant/server/web/dto/feed/FeedPreviewDto.java
  src/main/java/container/restaurant/server/web/dto/restaurant/RestaurantDetailDto.java
  src/main/java/container/restaurant/server/web/dto/restaurant/RestaurantNearInfoDto.java
  src/test/java/container/restaurant/server/domain/feed/recommend/RecommendFeedServiceTest.java
  src/test/java/container/restaurant/server/web/FeedControllerTest.java
  src/test/java/container/restaurant/server/web/RestaurantControllerTest.java
Labels: enhancement

#112 ✨ 액세스 토큰으로 로그인하는 기능
  build.gradle
  src/docs/asciidoc/index.adoc
  src/main/java/container/restaurant/server/ContainerRestaurantServerApplication.java
  src/main/java/container/restaurant/server/config/AppConfig.java
  src/main/java/container/restaurant/server/config/WebMvcConfig.java
  src/main/java/container/restaurant/server/config/auth/CustomOAuth2UserService.java
  src/main/java/container/restaurant/server/config/auth/SecurityConfig.java
  src/main/java/container/restaurant/server/config/auth/dto/OAuthAttributes.java
  src/main/java/container/restaurant/server/config/auth/dto/SessionUser.java
  src/main/java/container/restaurant/server/domain/push/PushToken.java
  src/main/java/container/restaurant/server/domain/user/AuthProvider.java
  src/main/java/container/restaurant/server/domain/user/Role.java
  src/main/java/container/restaurant/server/domain/user/User.java
  src/main/java/container/restaurant/server/domain/user/UserRepository.java
  src/main/java/container/restaurant/server/domain/user/UserService.java
  src/main/java/container/restaurant/server/domain/user/validator/NicknameConstraintValidator.java
  src/main/java/container/restaurant/server/exception/ExceptionAdvice.java
  src/main/java/container/restaurant/server/exception/UnauthorizedException.java
  src/main/java/container/restaurant/server/process/oauth/KakaoOAuthAgent.java
  src/main/java/container/restaurant/server/process/oauth/OAuthAgent.java
  src/main/java/container/restaurant/server/process/oauth/OAuthAgentFactory.java
  src/main/java/container/restaurant/server/web/UserController.java
  src/main/java/container/restaurant/server/web/dto/comment/CommentInfoDto.java
  src/main/java/container/restaurant/server/web/dto/statistics/StatisticsUserDto.java
  src/main/java/container/restaurant/server/web/dto/user/NicknameExistsDto.java
  src/main/java/container/restaurant/server/web/dto/user/UserDto.java
  src/main/java/container/restaurant/server/web/dto/user/UserInfoDto.java
  src/main/java/container/restaurant/server/web/dto/user/UserUpdateDto.java
  src/main/java/container/restaurant/server/web/linker/UserLinker.java
  src/test/java/container/restaurant/server/domain/comment/CommentRepositoryTest.java
  src/test/java/container/restaurant/server/domain/comment/CommentServiceTest.java
  src/test/java/container/restaurant/server/domain/comment/like/CommentLikeServiceTest.java
  src/test/java/container/restaurant/server/domain/feed/FeedRepositoryTest.java
  src/test/java/container/restaurant/server/domain/feed/FeedTest.java
  src/test/java/container/restaurant/server/domain/feed/like/FeedLikeRepositoryTest.java
  src/test/java/container/restaurant/server/domain/user/UserRepositoryTest.java
  src/test/java/container/restaurant/server/domain/user/UserTest.java
  src/test/java/container/restaurant/server/domain/user/scrap/ScrapFeedRepositoryTest.java
  src/test/java/container/restaurant/server/web/CommentControllerTest.java
  src/test/java/container/restaurant/server/web/FeedControllerTest.java
  src/test/java/container/restaurant/server/web/FeedLikeControllerTest.java
  src/test/java/container/restaurant/server/web/IndexControllerTest.java
  src/test/java/container/restaurant/server/web/ReportControllerTest.java
  src/test/java/container/restaurant/server/web/ScrapFeedControllerTest.java
  src/test/java/container/restaurant/server/web/UserControllerTest.java
  src/test/java/container/restaurant/server/web/base/BaseUserAndFeedControllerTest.java
  src/test/java/container/restaurant/server/web/base/BaseUserControllerTest.java
Labels: enhancement

#115 🏷️ User 레벨 속성 변경
  src/main/java/container/restaurant/server/domain/user/ContainerLevel.java
  src/main/java/container/restaurant/server/domain/user/User.java
  src/main/java/container/restaurant/server/web/dto/IndexDto.java
  src/main/java/container/restaurant/server/web/dto/comment/CommentInfoDto.java
  src/main/java/container/restaurant/server/web/dto/statistics/StatisticsUserDto.java
  src/main/java/container/restaurant/server/web/dto/user/UserDto.java
  src/test/java/container/restaurant/server/domain/user/UserTest.java
  src/test/java/container/restaurant/server/web/CommentControllerTest.java
  src/test/java/container/restaurant/server/web/IndexControllerTest.java
  src/test/java/container/restaurant/server/web/UserControllerTest.java
Labels: enhancement

#117 ♻️ 메뉴 용기, 식당 기능 일부 리팩토링
  src/main/java/container/restaurant/server/domain/feed/Feed.java
  src/main/java/container/restaurant/server/domain/feed/FeedService.java
  src/main/java/container/restaurant/server/domain/feed/container/Container.java
  src/main/java/container/restaurant/server/domain/feed/container/ContainerRepository.java
  src/main/java/container/restaurant/server/domain/feed/container/ContainerService.java
  src/main/java/container/restaurant/server/domain/restaurant/Restaurant.java
  src/main/java/container/restaurant/server/web/dto/feed/FeedInfoDto.java
  src/test/java/container/restaurant/server/domain/BaseServiceTest.java
  src/test/java/container/restaurant/server/domain/feed/FeedServiceTest.java
  src/test/java/container/restaurant/server/domain/feed/container/ContainerServiceTest.java
  src/test/java/container/restaurant/server/web/base/BaseUserAndFeedControllerTest.java
  src/test/java/container/restaurant/server/web/dto/feed/FeedInfoDtoTest.java
Labels: enhancement

#113 🐛 댓글 버그 수정
  src/main/java/container/restaurant/server/domain/comment/Comment.java
  src/main/java/container/restaurant/server/domain/comment/CommentRepository.java
  src/main/java/container/restaurant/server/domain/comment/CommentService.java
  src/main/java/container/restaurant/server/domain/comment/like/CommentLikeRepository.java
  src/main/java/container/restaurant/server/web/CommentController.java
  src/main/java/container/restaurant/server/web/dto/comment/CommentInfoDto.java
  src/test/java/container/restaurant/server/domain/comment/CommentServiceTest.java
  src/test/java/container/restaurant/server/domain/comment/like/CommentLikeRepositoryTest.java
  src/test/java/container/restaurant/server/web/CommentControllerTest.java
Labels: bug

#118 🐛 Docs 관련 버그 및 누락 수정
  src/docs/asciidoc/index.adoc
  src/main/java/container/restaurant/server/config/auth/LoginUserFilter.java
  src/main/java/container/restaurant/server/constant/Header.java
  src/main/java/container/restaurant/server/domain/contract/Contract.java
  src/main/java/container/restaurant/server/domain/feed/FeedService.java
  src/main/java/container/restaurant/server/domain/home/banner/Banner.java
  src/main/java/container/restaurant/server/web/UserController.java
  src/main/java/container/restaurant/server/web/dto/restaurant/RestaurantInfoDto.java
  src/test/java/container/restaurant/server/domain/feed/FeedServiceTest.java
  src/test/java/container/restaurant/server/web/CommentControllerTest.java
  src/test/java/container/restaurant/server/web/CommentLikeControllerTest.java
  src/test/java/container/restaurant/server/web/ContractControllerTest.java
  src/test/java/container/restaurant/server/web/FeedControllerTest.java
  src/test/java/container/restaurant/server/web/IndexControllerTest.java
  src/test/java/container/restaurant/server/web/UserControllerTest.java
Labels: bug
